trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy to Azure App Service'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.14' 

  - task: NuGetToolInstaller@1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: VSTest@2
    displayName: "Test"
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      version: '7.0.14' # Replace with the latest version

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy to Azure App Service"
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'
      appType: 'webApp'
      WebAppName: 'mfwebapp4567'
      packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
