name: Build and deploy .NET 8 Azure Function App - pratikappp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0'
  PROJECT_PATH: 'src/MyFunctionApp'
  PROJECT_FILE: 'MyFunctionApp.csproj'
  BUILD_OUTPUT_PATH: 'output'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC-based authentication
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore & Build .NET Project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          dotnet restore ${{ env.PROJECT_FILE }}
          dotnet build ${{ env.PROJECT_FILE }} --configuration Release --output ./${{ env.BUILD_OUTPUT_PATH }}

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DA5038A687544EDA6F8FC4EEDFDE64D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_003E7B7E001449B19E5A39167E0B771C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4D303B970C549B698CC77E9FA45C930 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'pratikappp'
          slot-name: 'Production'
          package: '${{ env.PROJECT_PATH }}/${{ env.BUILD_OUTPUT_PATH }}'
