name: Build and Deploy ASP.NET (.NET Framework 4.8) to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'pratikappp'   # 🔁 Replace with your Function App name
  PROJECT_FILE: 'aspnet-get-started/aspnet-get-started.csproj'
  PUBLISH_DIR: '${{ github.workspace }}\\publish_output'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: msbuild ${{ env.PROJECT_FILE }} /t:Restore

    - name: Build solution
      run: msbuild ${{ env.PROJECT_FILE }} /p:Configuration=Release

    - name: Publish app to folder
      run: |
        msbuild ${{ env.PROJECT_FILE }} `
          /p:Configuration=Release `
          /p:DeployOnBuild=true `
          /p:PublishProfile=FolderProfile `
          /p:PublishDir="${{ env.PUBLISH_DIR }}"

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.PUBLISH_DIR }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
