name: Build and Deploy Azure Function App (.NET 8)

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'your-function-app-name'   # Replace with your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'aspnet-get-started'
  PROJECT_FILE: 'aspnet-get-started/aspnet-get-started.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FILE }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_FILE }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_FILE }} --configuration Release --output ./publish_output --no-build

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './publish_output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
